// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3() {}
    static final FunctionDescriptor JxlParallelRunner$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final FunctionDescriptor JxlParallelRunner_UP$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JxlParallelRunner_UP$MH = RuntimeHelper.upcallHandle(JxlParallelRunner.class, "apply", constants$3.JxlParallelRunner_UP$FUNC);
    static final FunctionDescriptor JxlParallelRunner_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JxlParallelRunner_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$3.JxlParallelRunner_DOWN$FUNC
    );
    static final FunctionDescriptor JxlEncoderStatsCreate$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle JxlEncoderStatsCreate$MH = RuntimeHelper.downcallHandleVariadic(
        "JxlEncoderStatsCreate",
        constants$3.JxlEncoderStatsCreate$FUNC
    );
    static final FunctionDescriptor JxlEncoderStatsDestroy$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderStatsDestroy$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderStatsDestroy",
        constants$3.JxlEncoderStatsDestroy$FUNC
    );
    static final FunctionDescriptor JxlEncoderStatsGet$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JxlEncoderStatsGet$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderStatsGet",
        constants$3.JxlEncoderStatsGet$FUNC
    );
    static final FunctionDescriptor JxlEncoderStatsMerge$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderStatsMerge$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderStatsMerge",
        constants$3.JxlEncoderStatsMerge$FUNC
    );
}


