// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$13 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$13() {}
    static final FunctionDescriptor JxlDecoderReset$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderReset$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderReset",
        constants$13.JxlDecoderReset$FUNC
    );
    static final FunctionDescriptor JxlDecoderDestroy$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderDestroy$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderDestroy",
        constants$13.JxlDecoderDestroy$FUNC
    );
    static final FunctionDescriptor JxlDecoderRewind$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderRewind$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderRewind",
        constants$13.JxlDecoderRewind$FUNC
    );
    static final FunctionDescriptor JxlDecoderSkipFrames$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlDecoderSkipFrames$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSkipFrames",
        constants$13.JxlDecoderSkipFrames$FUNC
    );
    static final FunctionDescriptor JxlDecoderSkipCurrentFrame$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderSkipCurrentFrame$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSkipCurrentFrame",
        constants$13.JxlDecoderSkipCurrentFrame$FUNC
    );
    static final FunctionDescriptor JxlDecoderSetParallelRunner$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderSetParallelRunner$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSetParallelRunner",
        constants$13.JxlDecoderSetParallelRunner$FUNC
    );
}


