// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final FunctionDescriptor JxlEncoderVersion$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle JxlEncoderVersion$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderVersion",
        constants$4.JxlEncoderVersion$FUNC
    );
    static final FunctionDescriptor JxlEncoderCreate$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderCreate$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderCreate",
        constants$4.JxlEncoderCreate$FUNC
    );
    static final FunctionDescriptor JxlEncoderReset$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderReset$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderReset",
        constants$4.JxlEncoderReset$FUNC
    );
    static final FunctionDescriptor JxlEncoderDestroy$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderDestroy$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderDestroy",
        constants$4.JxlEncoderDestroy$FUNC
    );
    static final FunctionDescriptor JxlEncoderSetCms$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("set_fields_data"),
            Constants$root.C_POINTER$LAYOUT.withName("set_fields_from_icc"),
            Constants$root.C_POINTER$LAYOUT.withName("init_data"),
            Constants$root.C_POINTER$LAYOUT.withName("init"),
            Constants$root.C_POINTER$LAYOUT.withName("get_src_buf"),
            Constants$root.C_POINTER$LAYOUT.withName("get_dst_buf"),
            Constants$root.C_POINTER$LAYOUT.withName("run"),
            Constants$root.C_POINTER$LAYOUT.withName("destroy")
        )
    );
    static final MethodHandle JxlEncoderSetCms$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderSetCms",
        constants$4.JxlEncoderSetCms$FUNC
    );
    static final FunctionDescriptor JxlEncoderSetParallelRunner$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderSetParallelRunner$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderSetParallelRunner",
        constants$4.JxlEncoderSetParallelRunner$FUNC
    );
}


