// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$7 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$7() {}
    static final FunctionDescriptor JxlEncoderChunkedImageFrameAddPart$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlEncoderChunkedImageFrameAddPart$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderChunkedImageFrameAddPart",
        constants$7.JxlEncoderChunkedImageFrameAddPart$FUNC
    );
    static final FunctionDescriptor JxlEncoderSetExtraChannelBuffer$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JxlEncoderSetExtraChannelBuffer$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderSetExtraChannelBuffer",
        constants$7.JxlEncoderSetExtraChannelBuffer$FUNC
    );
    static final FunctionDescriptor JxlEncoderAddBox$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JxlEncoderAddBox$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderAddBox",
        constants$7.JxlEncoderAddBox$FUNC
    );
    static final FunctionDescriptor JxlEncoderUseBoxes$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderUseBoxes$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderUseBoxes",
        constants$7.JxlEncoderUseBoxes$FUNC
    );
    static final FunctionDescriptor JxlEncoderCloseBoxes$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderCloseBoxes$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderCloseBoxes",
        constants$7.JxlEncoderCloseBoxes$FUNC
    );
    static final FunctionDescriptor JxlEncoderCloseFrames$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderCloseFrames$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderCloseFrames",
        constants$7.JxlEncoderCloseFrames$FUNC
    );
}


