// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$19 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$19() {}
    static final FunctionDescriptor JxlImageOutInitCallback_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlImageOutInitCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$19.JxlImageOutInitCallback_DOWN$FUNC
    );
    static final FunctionDescriptor JxlImageOutRunCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor JxlImageOutRunCallback_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlImageOutRunCallback_UP$MH = RuntimeHelper.upcallHandle(JxlImageOutRunCallback.class, "apply", constants$19.JxlImageOutRunCallback_UP$FUNC);
    static final FunctionDescriptor JxlImageOutRunCallback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlImageOutRunCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$19.JxlImageOutRunCallback_DOWN$FUNC
    );
    static final FunctionDescriptor JxlImageOutDestroyCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor JxlImageOutDestroyCallback_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlImageOutDestroyCallback_UP$MH = RuntimeHelper.upcallHandle(JxlImageOutDestroyCallback.class, "apply", constants$19.JxlImageOutDestroyCallback_UP$FUNC);
    static final FunctionDescriptor JxlImageOutDestroyCallback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlImageOutDestroyCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$19.JxlImageOutDestroyCallback_DOWN$FUNC
    );
    static final FunctionDescriptor JxlDecoderSetImageOutCallback$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderSetImageOutCallback$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSetImageOutCallback",
        constants$19.JxlDecoderSetImageOutCallback$FUNC
    );
}


