// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$16 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$16() {}
    static final FunctionDescriptor JxlDecoderGetExtraChannelName$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlDecoderGetExtraChannelName$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderGetExtraChannelName",
        constants$16.JxlDecoderGetExtraChannelName$FUNC
    );
    static final FunctionDescriptor JxlDecoderGetColorAsEncodedProfile$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderGetColorAsEncodedProfile$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderGetColorAsEncodedProfile",
        constants$16.JxlDecoderGetColorAsEncodedProfile$FUNC
    );
    static final FunctionDescriptor JxlDecoderGetICCProfileSize$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderGetICCProfileSize$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderGetICCProfileSize",
        constants$16.JxlDecoderGetICCProfileSize$FUNC
    );
    static final FunctionDescriptor JxlDecoderGetColorAsICCProfile$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlDecoderGetColorAsICCProfile$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderGetColorAsICCProfile",
        constants$16.JxlDecoderGetColorAsICCProfile$FUNC
    );
    static final FunctionDescriptor JxlDecoderSetPreferredColorProfile$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderSetPreferredColorProfile$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSetPreferredColorProfile",
        constants$16.JxlDecoderSetPreferredColorProfile$FUNC
    );
    static final FunctionDescriptor JxlDecoderSetDesiredIntensityTarget$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JxlDecoderSetDesiredIntensityTarget$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSetDesiredIntensityTarget",
        constants$16.JxlDecoderSetDesiredIntensityTarget$FUNC
    );
}


