// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final FunctionDescriptor jpegxl_cms_set_fields_from_icc_func$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor jpegxl_cms_set_fields_from_icc_func_UP$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle jpegxl_cms_set_fields_from_icc_func_UP$MH = RuntimeHelper.upcallHandle(jpegxl_cms_set_fields_from_icc_func.class, "apply", constants$0.jpegxl_cms_set_fields_from_icc_func_UP$FUNC);
    static final FunctionDescriptor jpegxl_cms_set_fields_from_icc_func_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle jpegxl_cms_set_fields_from_icc_func_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$0.jpegxl_cms_set_fields_from_icc_func_DOWN$FUNC
    );
    static final FunctionDescriptor jpegxl_cms_init_func$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final FunctionDescriptor jpegxl_cms_init_func_UP$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle jpegxl_cms_init_func_UP$MH = RuntimeHelper.upcallHandle(jpegxl_cms_init_func.class, "apply", constants$0.jpegxl_cms_init_func_UP$FUNC);
    static final FunctionDescriptor jpegxl_cms_init_func_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle jpegxl_cms_init_func_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$0.jpegxl_cms_init_func_DOWN$FUNC
    );
    static final FunctionDescriptor jpegxl_cms_get_buffer_func$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final FunctionDescriptor jpegxl_cms_get_buffer_func_UP$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle jpegxl_cms_get_buffer_func_UP$MH = RuntimeHelper.upcallHandle(jpegxl_cms_get_buffer_func.class, "apply", constants$0.jpegxl_cms_get_buffer_func_UP$FUNC);
    static final FunctionDescriptor jpegxl_cms_get_buffer_func_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle jpegxl_cms_get_buffer_func_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$0.jpegxl_cms_get_buffer_func_DOWN$FUNC
    );
}


