// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$22 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$22() {}
    static final FunctionDescriptor JxlDecoderFlushImage$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderFlushImage$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderFlushImage",
        constants$22.JxlDecoderFlushImage$FUNC
    );
    static final FunctionDescriptor JxlDecoderSetImageOutBitDepth$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderSetImageOutBitDepth$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSetImageOutBitDepth",
        constants$22.JxlDecoderSetImageOutBitDepth$FUNC
    );
    static final FunctionDescriptor JxlThreadParallelRunner$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JxlThreadParallelRunner$MH = RuntimeHelper.downcallHandle(
        "JxlThreadParallelRunner",
        constants$22.JxlThreadParallelRunner$FUNC
    );
    static final FunctionDescriptor JxlThreadParallelRunnerCreate$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlThreadParallelRunnerCreate$MH = RuntimeHelper.downcallHandle(
        "JxlThreadParallelRunnerCreate",
        constants$22.JxlThreadParallelRunnerCreate$FUNC
    );
    static final FunctionDescriptor JxlThreadParallelRunnerDestroy$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlThreadParallelRunnerDestroy$MH = RuntimeHelper.downcallHandle(
        "JxlThreadParallelRunnerDestroy",
        constants$22.JxlThreadParallelRunnerDestroy$FUNC
    );
    static final FunctionDescriptor JxlThreadParallelRunnerDefaultNumWorkerThreads$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle JxlThreadParallelRunnerDefaultNumWorkerThreads$MH = RuntimeHelper.downcallHandleVariadic(
        "JxlThreadParallelRunnerDefaultNumWorkerThreads",
        constants$22.JxlThreadParallelRunnerDefaultNumWorkerThreads$FUNC
    );
}


