// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$10 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$10() {}
    static final FunctionDescriptor JxlEncoderUseContainer$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JxlEncoderUseContainer$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderUseContainer",
        constants$10.JxlEncoderUseContainer$FUNC
    );
    static final FunctionDescriptor JxlEncoderStoreJPEGMetadata$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JxlEncoderStoreJPEGMetadata$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderStoreJPEGMetadata",
        constants$10.JxlEncoderStoreJPEGMetadata$FUNC
    );
    static final FunctionDescriptor JxlEncoderSetCodestreamLevel$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JxlEncoderSetCodestreamLevel$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderSetCodestreamLevel",
        constants$10.JxlEncoderSetCodestreamLevel$FUNC
    );
    static final FunctionDescriptor JxlEncoderGetRequiredCodestreamLevel$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderGetRequiredCodestreamLevel$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderGetRequiredCodestreamLevel",
        constants$10.JxlEncoderGetRequiredCodestreamLevel$FUNC
    );
    static final FunctionDescriptor JxlEncoderSetFrameLossless$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JxlEncoderSetFrameLossless$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderSetFrameLossless",
        constants$10.JxlEncoderSetFrameLossless$FUNC
    );
    static final FunctionDescriptor JxlEncoderSetFrameDistance$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JxlEncoderSetFrameDistance$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderSetFrameDistance",
        constants$10.JxlEncoderSetFrameDistance$FUNC
    );
}


