// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$9 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$9() {}
    static final FunctionDescriptor JxlEncoderSetBasicInfo$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderSetBasicInfo$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderSetBasicInfo",
        constants$9.JxlEncoderSetBasicInfo$FUNC
    );
    static final FunctionDescriptor JxlEncoderInitExtraChannelInfo$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderInitExtraChannelInfo$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderInitExtraChannelInfo",
        constants$9.JxlEncoderInitExtraChannelInfo$FUNC
    );
    static final FunctionDescriptor JxlEncoderSetExtraChannelInfo$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderSetExtraChannelInfo$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderSetExtraChannelInfo",
        constants$9.JxlEncoderSetExtraChannelInfo$FUNC
    );
    static final FunctionDescriptor JxlEncoderSetExtraChannelName$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlEncoderSetExtraChannelName$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderSetExtraChannelName",
        constants$9.JxlEncoderSetExtraChannelName$FUNC
    );
    static final FunctionDescriptor JxlEncoderFrameSettingsSetOption$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlEncoderFrameSettingsSetOption$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderFrameSettingsSetOption",
        constants$9.JxlEncoderFrameSettingsSetOption$FUNC
    );
    static final FunctionDescriptor JxlEncoderFrameSettingsSetFloatOption$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JxlEncoderFrameSettingsSetFloatOption$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderFrameSettingsSetFloatOption",
        constants$9.JxlEncoderFrameSettingsSetFloatOption$FUNC
    );
}


