// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$20 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$20() {}
    static final FunctionDescriptor JxlDecoderSetMultithreadedImageOutCallback$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderSetMultithreadedImageOutCallback$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSetMultithreadedImageOutCallback",
        constants$20.JxlDecoderSetMultithreadedImageOutCallback$FUNC
    );
    static final FunctionDescriptor JxlDecoderExtraChannelBufferSize$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JxlDecoderExtraChannelBufferSize$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderExtraChannelBufferSize",
        constants$20.JxlDecoderExtraChannelBufferSize$FUNC
    );
    static final FunctionDescriptor JxlDecoderSetExtraChannelBuffer$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JxlDecoderSetExtraChannelBuffer$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSetExtraChannelBuffer",
        constants$20.JxlDecoderSetExtraChannelBuffer$FUNC
    );
    static final FunctionDescriptor JxlDecoderSetJPEGBuffer$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlDecoderSetJPEGBuffer$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSetJPEGBuffer",
        constants$20.JxlDecoderSetJPEGBuffer$FUNC
    );
    static final FunctionDescriptor JxlDecoderReleaseJPEGBuffer$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderReleaseJPEGBuffer$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderReleaseJPEGBuffer",
        constants$20.JxlDecoderReleaseJPEGBuffer$FUNC
    );
    static final FunctionDescriptor JxlDecoderSetBoxBuffer$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlDecoderSetBoxBuffer$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSetBoxBuffer",
        constants$20.JxlDecoderSetBoxBuffer$FUNC
    );
}


