// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$8 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$8() {}
    static final FunctionDescriptor JxlEncoderCloseInput$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderCloseInput$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderCloseInput",
        constants$8.JxlEncoderCloseInput$FUNC
    );
    static final FunctionDescriptor JxlEncoderSetColorEncoding$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderSetColorEncoding$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderSetColorEncoding",
        constants$8.JxlEncoderSetColorEncoding$FUNC
    );
    static final FunctionDescriptor JxlEncoderSetICCProfile$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlEncoderSetICCProfile$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderSetICCProfile",
        constants$8.JxlEncoderSetICCProfile$FUNC
    );
    static final FunctionDescriptor JxlEncoderInitBasicInfo$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderInitBasicInfo$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderInitBasicInfo",
        constants$8.JxlEncoderInitBasicInfo$FUNC
    );
    static final FunctionDescriptor JxlEncoderInitFrameHeader$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderInitFrameHeader$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderInitFrameHeader",
        constants$8.JxlEncoderInitFrameHeader$FUNC
    );
    static final FunctionDescriptor JxlEncoderInitBlendInfo$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderInitBlendInfo$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderInitBlendInfo",
        constants$8.JxlEncoderInitBlendInfo$FUNC
    );
}


