// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$14 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$14() {}
    static final FunctionDescriptor JxlDecoderSizeHintBasicInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderSizeHintBasicInfo$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSizeHintBasicInfo",
        constants$14.JxlDecoderSizeHintBasicInfo$FUNC
    );
    static final FunctionDescriptor JxlDecoderSubscribeEvents$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JxlDecoderSubscribeEvents$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSubscribeEvents",
        constants$14.JxlDecoderSubscribeEvents$FUNC
    );
    static final FunctionDescriptor JxlDecoderSetKeepOrientation$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JxlDecoderSetKeepOrientation$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSetKeepOrientation",
        constants$14.JxlDecoderSetKeepOrientation$FUNC
    );
    static final FunctionDescriptor JxlDecoderSetUnpremultiplyAlpha$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JxlDecoderSetUnpremultiplyAlpha$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSetUnpremultiplyAlpha",
        constants$14.JxlDecoderSetUnpremultiplyAlpha$FUNC
    );
    static final FunctionDescriptor JxlDecoderSetRenderSpotcolors$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JxlDecoderSetRenderSpotcolors$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSetRenderSpotcolors",
        constants$14.JxlDecoderSetRenderSpotcolors$FUNC
    );
    static final FunctionDescriptor JxlDecoderSetCoalescing$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JxlDecoderSetCoalescing$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSetCoalescing",
        constants$14.JxlDecoderSetCoalescing$FUNC
    );
}


