// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}
    static final FunctionDescriptor JxlDebugImageCallback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDebugImageCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$12.JxlDebugImageCallback_DOWN$FUNC
    );
    static final FunctionDescriptor JxlEncoderSetDebugImageCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderSetDebugImageCallback$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderSetDebugImageCallback",
        constants$12.JxlEncoderSetDebugImageCallback$FUNC
    );
    static final FunctionDescriptor JxlEncoderCollectStats$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderCollectStats$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderCollectStats",
        constants$12.JxlEncoderCollectStats$FUNC
    );
    static final FunctionDescriptor JxlDecoderVersion$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle JxlDecoderVersion$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderVersion",
        constants$12.JxlDecoderVersion$FUNC
    );
    static final FunctionDescriptor JxlSignatureCheck$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlSignatureCheck$MH = RuntimeHelper.downcallHandle(
        "JxlSignatureCheck",
        constants$12.JxlSignatureCheck$FUNC
    );
    static final FunctionDescriptor JxlDecoderCreate$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderCreate$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderCreate",
        constants$12.JxlDecoderCreate$FUNC
    );
}


