// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final FunctionDescriptor JxlEncoderAddJPEGFrame$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlEncoderAddJPEGFrame$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderAddJPEGFrame",
        constants$6.JxlEncoderAddJPEGFrame$FUNC
    );
    static final FunctionDescriptor JxlEncoderAddImageFrame$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlEncoderAddImageFrame$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderAddImageFrame",
        constants$6.JxlEncoderAddImageFrame$FUNC
    );
    static final FunctionDescriptor JxlEncoderOutputCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final FunctionDescriptor JxlEncoderOutputCallback_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlEncoderOutputCallback_UP$MH = RuntimeHelper.upcallHandle(JxlEncoderOutputCallback.class, "apply", constants$6.JxlEncoderOutputCallback_UP$FUNC);
    static final FunctionDescriptor JxlEncoderOutputCallback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlEncoderOutputCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$6.JxlEncoderOutputCallback_DOWN$FUNC
    );
    static final FunctionDescriptor JxlEncoderSetOutputCallback$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderSetOutputCallback$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderSetOutputCallback",
        constants$6.JxlEncoderSetOutputCallback$FUNC
    );
    static final FunctionDescriptor JxlEncoderChunkedImageFrameStart$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlEncoderChunkedImageFrameStart$MH = RuntimeHelper.downcallHandle(
        "JxlEncoderChunkedImageFrameStart",
        constants$6.JxlEncoderChunkedImageFrameStart$FUNC
    );
}


