// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1() {}
    static final FunctionDescriptor jpegxl_cms_run_func$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final FunctionDescriptor jpegxl_cms_run_func_UP$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle jpegxl_cms_run_func_UP$MH = RuntimeHelper.upcallHandle(jpegxl_cms_run_func.class, "apply", constants$1.jpegxl_cms_run_func_UP$FUNC);
    static final FunctionDescriptor jpegxl_cms_run_func_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle jpegxl_cms_run_func_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$1.jpegxl_cms_run_func_DOWN$FUNC
    );
    static final FunctionDescriptor jpegxl_cms_destroy_func$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor jpegxl_cms_destroy_func_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle jpegxl_cms_destroy_func_UP$MH = RuntimeHelper.upcallHandle(jpegxl_cms_destroy_func.class, "apply", constants$1.jpegxl_cms_destroy_func_UP$FUNC);
    static final FunctionDescriptor jpegxl_cms_destroy_func_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle jpegxl_cms_destroy_func_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$1.jpegxl_cms_destroy_func_DOWN$FUNC
    );
    static final FunctionDescriptor jpegxl_alloc_func$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final FunctionDescriptor jpegxl_alloc_func_UP$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle jpegxl_alloc_func_UP$MH = RuntimeHelper.upcallHandle(jpegxl_alloc_func.class, "apply", constants$1.jpegxl_alloc_func_UP$FUNC);
    static final FunctionDescriptor jpegxl_alloc_func_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle jpegxl_alloc_func_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$1.jpegxl_alloc_func_DOWN$FUNC
    );
}


