// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$15 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$15() {}
    static final FunctionDescriptor JxlDecoderProcessInput$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderProcessInput$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderProcessInput",
        constants$15.JxlDecoderProcessInput$FUNC
    );
    static final FunctionDescriptor JxlDecoderSetInput$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlDecoderSetInput$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSetInput",
        constants$15.JxlDecoderSetInput$FUNC
    );
    static final FunctionDescriptor JxlDecoderReleaseInput$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderReleaseInput$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderReleaseInput",
        constants$15.JxlDecoderReleaseInput$FUNC
    );
    static final FunctionDescriptor JxlDecoderCloseInput$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderCloseInput$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderCloseInput",
        constants$15.JxlDecoderCloseInput$FUNC
    );
    static final FunctionDescriptor JxlDecoderGetBasicInfo$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderGetBasicInfo$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderGetBasicInfo",
        constants$15.JxlDecoderGetBasicInfo$FUNC
    );
    static final FunctionDescriptor JxlDecoderGetExtraChannelInfo$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderGetExtraChannelInfo$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderGetExtraChannelInfo",
        constants$15.JxlDecoderGetExtraChannelInfo$FUNC
    );
}


