// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*jpegxl_cms_destroy_func)(void*);
 * }
 */
public interface jpegxl_cms_destroy_func {

    void apply(java.lang.foreign.MemorySegment run_opaque);
    static MemorySegment allocate(jpegxl_cms_destroy_func fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$1.jpegxl_cms_destroy_func_UP$MH, fi, constants$1.jpegxl_cms_destroy_func$FUNC, scope);
    }
    static jpegxl_cms_destroy_func ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _run_opaque) -> {
            try {
                constants$1.jpegxl_cms_destroy_func_DOWN$MH.invokeExact(symbol, _run_opaque);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


