// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void* (*jpegxl_alloc_func)(void* opaque,unsigned long size);
 * }
 */
public interface jpegxl_alloc_func {

    java.lang.foreign.MemorySegment apply(java.lang.foreign.MemorySegment opaque, long size);
    static MemorySegment allocate(jpegxl_alloc_func fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$1.jpegxl_alloc_func_UP$MH, fi, constants$1.jpegxl_alloc_func$FUNC, scope);
    }
    static jpegxl_alloc_func ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _opaque, long _size) -> {
            try {
                return (java.lang.foreign.MemorySegment)constants$1.jpegxl_alloc_func_DOWN$MH.invokeExact(symbol, _opaque, _size);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


