// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     JxlBitDepthType type;
 *     uint32_t bits_per_sample;
 *     uint32_t exponent_bits_per_sample;
 * };
 * }
 */
public class JxlBitDepth {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("type"),
        Constants$root.C_INT$LAYOUT.withName("bits_per_sample"),
        Constants$root.C_INT$LAYOUT.withName("exponent_bits_per_sample")
    );
    public static MemoryLayout $LAYOUT() {
        return JxlBitDepth.$struct$LAYOUT;
    }
    static final VarHandle type$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("type"));
    public static VarHandle type$VH() {
        return JxlBitDepth.type$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * JxlBitDepthType type;
     * }
     */
    public static int type$get(MemorySegment seg) {
        return (int)JxlBitDepth.type$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * JxlBitDepthType type;
     * }
     */
    public static void type$set(MemorySegment seg, int x) {
        JxlBitDepth.type$VH.set(seg, x);
    }
    public static int type$get(MemorySegment seg, long index) {
        return (int)JxlBitDepth.type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void type$set(MemorySegment seg, long index, int x) {
        JxlBitDepth.type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle bits_per_sample$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("bits_per_sample"));
    public static VarHandle bits_per_sample$VH() {
        return JxlBitDepth.bits_per_sample$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t bits_per_sample;
     * }
     */
    public static int bits_per_sample$get(MemorySegment seg) {
        return (int)JxlBitDepth.bits_per_sample$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t bits_per_sample;
     * }
     */
    public static void bits_per_sample$set(MemorySegment seg, int x) {
        JxlBitDepth.bits_per_sample$VH.set(seg, x);
    }
    public static int bits_per_sample$get(MemorySegment seg, long index) {
        return (int)JxlBitDepth.bits_per_sample$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void bits_per_sample$set(MemorySegment seg, long index, int x) {
        JxlBitDepth.bits_per_sample$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle exponent_bits_per_sample$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("exponent_bits_per_sample"));
    public static VarHandle exponent_bits_per_sample$VH() {
        return JxlBitDepth.exponent_bits_per_sample$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t exponent_bits_per_sample;
     * }
     */
    public static int exponent_bits_per_sample$get(MemorySegment seg) {
        return (int)JxlBitDepth.exponent_bits_per_sample$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t exponent_bits_per_sample;
     * }
     */
    public static void exponent_bits_per_sample$set(MemorySegment seg, int x) {
        JxlBitDepth.exponent_bits_per_sample$VH.set(seg, x);
    }
    public static int exponent_bits_per_sample$get(MemorySegment seg, long index) {
        return (int)JxlBitDepth.exponent_bits_per_sample$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void exponent_bits_per_sample$set(MemorySegment seg, long index, int x) {
        JxlBitDepth.exponent_bits_per_sample$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


