// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct JxlEncoderStruct JxlEncoder;
 * }
 */
public final class JxlEncoder {

    // Suppresses default constructor, ensuring non-instantiability.
    private JxlEncoder() {}
}


