// Generated by jextract

package com.unascribed.jxljxl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*JxlImageOutRunCallback)(void* run_opaque,unsigned long thread_id,unsigned long x,unsigned long y,unsigned long num_pixels,void* pixels);
 * }
 */
public interface JxlImageOutRunCallback {

    void apply(java.lang.foreign.MemorySegment run_opaque, long thread_id, long x, long y, long num_pixels, java.lang.foreign.MemorySegment pixels);
    static MemorySegment allocate(JxlImageOutRunCallback fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$19.JxlImageOutRunCallback_UP$MH, fi, constants$19.JxlImageOutRunCallback$FUNC, scope);
    }
    static JxlImageOutRunCallback ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _run_opaque, long _thread_id, long _x, long _y, long _num_pixels, java.lang.foreign.MemorySegment _pixels) -> {
            try {
                constants$19.JxlImageOutRunCallback_DOWN$MH.invokeExact(symbol, _run_opaque, _thread_id, _x, _y, _num_pixels, _pixels);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


